//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace ConvExt.HtmlToMarkdown.Strings;

using System;
using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class HtmlToMarkdown
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal HtmlToMarkdown() { }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                ResourceManager temp = new ResourceManager("ConvExt.HtmlToMarkdown.Strings.HtmlToMarkdown", typeof(HtmlToMarkdown).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static CultureInfo? Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    private static string Get(string key) =>
        ResourceManager.GetString(key, resourceCulture) ?? string.Empty;

    internal static string ShortDisplayTitle => Get(nameof(ShortDisplayTitle));
    internal static string LongDisplayTitle => Get(nameof(LongDisplayTitle));
    internal static string Description => Get(nameof(Description));
    internal static string AccessibleName => Get(nameof(AccessibleName));

    internal static string ConfigurationTitle => Get(nameof(ConfigurationTitle));

    internal static string Input => Get(nameof(Input));
    internal static string Output => Get(nameof(Output));

    internal static string GithubFlavoredTitle => Get(nameof(GithubFlavoredTitle));
    internal static string GithubFlavoredDescription => Get(nameof(GithubFlavoredDescription));

    internal static string SmartHrefTitle => Get(nameof(SmartHrefTitle));
    internal static string SmartHrefDescription => Get(nameof(SmartHrefDescription));

    internal static string RemoveCommentsTitle => Get(nameof(RemoveCommentsTitle));
    internal static string RemoveCommentsDescription => Get(nameof(RemoveCommentsDescription));

    internal static string UnknownTagsTitle => Get(nameof(UnknownTagsTitle));
    internal static string UnknownTagsDescription => Get(nameof(UnknownTagsDescription));
    internal static string UnknownTagsPassThrough => Get(nameof(UnknownTagsPassThrough));
    internal static string UnknownTagsDrop => Get(nameof(UnknownTagsDrop));
    internal static string UnknownTagsBypass => Get(nameof(UnknownTagsBypass));
    internal static string UnknownTagsRaise => Get(nameof(UnknownTagsRaise));

    internal static string BulletCharTitle => Get(nameof(BulletCharTitle));
    internal static string BulletCharDescription => Get(nameof(BulletCharDescription));
    internal static string BulletDash => Get(nameof(BulletDash));
    internal static string BulletStar => Get(nameof(BulletStar));
    internal static string BulletPlus => Get(nameof(BulletPlus));

    internal static string DefaultCodeLanguageTitle => Get(nameof(DefaultCodeLanguageTitle));
    internal static string DefaultCodeLanguageDescription => Get(nameof(DefaultCodeLanguageDescription));

    internal static string TableWithoutHeaderTitle => Get(nameof(TableWithoutHeaderTitle));
    internal static string TableWithoutHeaderDescription => Get(nameof(TableWithoutHeaderDescription));
    internal static string TableWithoutHeaderDefault => Get(nameof(TableWithoutHeaderDefault));
    internal static string TableWithoutHeaderEmptyRow => Get(nameof(TableWithoutHeaderEmptyRow));

    internal static string ErrorBarTitle => Get(nameof(ErrorBarTitle));
}
